### ISSUE TITLE
Gem fails to install on OS X

### ISSUE THREAD

**Issue by romulof** [brauliobo/less2sass#2]
```bash
 $  sudo gem install less2sass
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/less2sass
```

Try using `/usr/local/bin`

**Comment by brauliobo** [comment]
@romulof, please try this fix and submit a PR. Besides, give me some examples of `/usr/local/bin` examples in gems

**Comment by pnomolos** [comment]
This is likely due the El Capitan beta preventing anyone (including root) from writing to certain directories, and not a bug.

**Comment by brauliobo** [comment]
@pnomolos gonna believe you, closing this
