### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by cthiebault** [brauliobo/less2sass#7]
Thanks for your great work :-)

I've created a Docker image to use your converter without installing Ruby:
https://hub.docker.com/r/cthiebault/less2sass/

**Comment by swrobel** [comment]
Hm, which platform doesn't come with ruby installed?

**Comment by cthiebault** [comment]
At least Ubuntu & Debian...

**Comment by swrobel** [comment]
Wow, I did not realize that! Adding your docker image to the README
